// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GStruct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_GStruct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_GStruct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_GStruct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_GStruct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GStruct_2eproto;
namespace Protocol {
class Character;
struct CharacterDefaultTypeInternal;
extern CharacterDefaultTypeInternal _Character_default_instance_;
class Character_Attack;
struct Character_AttackDefaultTypeInternal;
extern Character_AttackDefaultTypeInternal _Character_Attack_default_instance_;
class Equip_Item;
struct Equip_ItemDefaultTypeInternal;
extern Equip_ItemDefaultTypeInternal _Equip_Item_default_instance_;
class Time;
struct TimeDefaultTypeInternal;
extern TimeDefaultTypeInternal _Time_default_instance_;
class Zombie;
struct ZombieDefaultTypeInternal;
extern ZombieDefaultTypeInternal _Zombie_default_instance_;
class ZombieDataList;
struct ZombieDataListDefaultTypeInternal;
extern ZombieDataListDefaultTypeInternal _ZombieDataList_default_instance_;
class jump;
struct jumpDefaultTypeInternal;
extern jumpDefaultTypeInternal _jump_default_instance_;
class run;
struct runDefaultTypeInternal;
extern runDefaultTypeInternal _run_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::Character* Arena::CreateMaybeMessage<::Protocol::Character>(Arena*);
template<> ::Protocol::Character_Attack* Arena::CreateMaybeMessage<::Protocol::Character_Attack>(Arena*);
template<> ::Protocol::Equip_Item* Arena::CreateMaybeMessage<::Protocol::Equip_Item>(Arena*);
template<> ::Protocol::Time* Arena::CreateMaybeMessage<::Protocol::Time>(Arena*);
template<> ::Protocol::Zombie* Arena::CreateMaybeMessage<::Protocol::Zombie>(Arena*);
template<> ::Protocol::ZombieDataList* Arena::CreateMaybeMessage<::Protocol::ZombieDataList>(Arena*);
template<> ::Protocol::jump* Arena::CreateMaybeMessage<::Protocol::jump>(Arena*);
template<> ::Protocol::run* Arena::CreateMaybeMessage<::Protocol::run>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class Character final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Character) */ {
 public:
  inline Character() : Character(nullptr) {}
  ~Character() override;
  explicit PROTOBUF_CONSTEXPR Character(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Character(const Character& from);
  Character(Character&& from) noexcept
    : Character() {
    *this = ::std::move(from);
  }

  inline Character& operator=(const Character& from) {
    CopyFrom(from);
    return *this;
  }
  inline Character& operator=(Character&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Character& default_instance() {
    return *internal_default_instance();
  }
  static inline const Character* internal_default_instance() {
    return reinterpret_cast<const Character*>(
               &_Character_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Character& a, Character& b) {
    a.Swap(&b);
  }
  inline void Swap(Character* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Character* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Character* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Character>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Character& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Character& from) {
    Character::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Character* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Character";
  }
  protected:
  explicit Character(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayeridFieldNumber = 1,
    kCharactertypeFieldNumber = 2,
    kPacketTypeFieldNumber = 3,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
    kZFieldNumber = 6,
    kPitchFieldNumber = 7,
    kYawFieldNumber = 8,
    kRollFieldNumber = 9,
    kHpFieldNumber = 10,
    kIsingameFieldNumber = 11,
  };
  // uint32 playerid = 1;
  void clear_playerid();
  uint32_t playerid() const;
  void set_playerid(uint32_t value);
  private:
  uint32_t _internal_playerid() const;
  void _internal_set_playerid(uint32_t value);
  public:

  // uint32 charactertype = 2;
  void clear_charactertype();
  uint32_t charactertype() const;
  void set_charactertype(uint32_t value);
  private:
  uint32_t _internal_charactertype() const;
  void _internal_set_charactertype(uint32_t value);
  public:

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // float x = 4;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 5;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 6;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float pitch = 7;
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // float yaw = 8;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // float roll = 9;
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // float hp = 10;
  void clear_hp();
  float hp() const;
  void set_hp(float value);
  private:
  float _internal_hp() const;
  void _internal_set_hp(float value);
  public:

  // bool isingame = 11;
  void clear_isingame();
  bool isingame() const;
  void set_isingame(bool value);
  private:
  bool _internal_isingame() const;
  void _internal_set_isingame(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Character)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t playerid_;
    uint32_t charactertype_;
    uint32_t packet_type_;
    float x_;
    float y_;
    float z_;
    float pitch_;
    float yaw_;
    float roll_;
    float hp_;
    bool isingame_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// -------------------------------------------------------------------

class Zombie final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Zombie) */ {
 public:
  inline Zombie() : Zombie(nullptr) {}
  ~Zombie() override;
  explicit PROTOBUF_CONSTEXPR Zombie(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Zombie(const Zombie& from);
  Zombie(Zombie&& from) noexcept
    : Zombie() {
    *this = ::std::move(from);
  }

  inline Zombie& operator=(const Zombie& from) {
    CopyFrom(from);
    return *this;
  }
  inline Zombie& operator=(Zombie&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Zombie& default_instance() {
    return *internal_default_instance();
  }
  static inline const Zombie* internal_default_instance() {
    return reinterpret_cast<const Zombie*>(
               &_Zombie_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Zombie& a, Zombie& b) {
    a.Swap(&b);
  }
  inline void Swap(Zombie* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Zombie* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Zombie* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Zombie>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Zombie& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Zombie& from) {
    Zombie::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Zombie* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Zombie";
  }
  protected:
  explicit Zombie(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kZombieidFieldNumber = 1,
    kZombietypeFieldNumber = 2,
    kPacketTypeFieldNumber = 3,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
    kZFieldNumber = 6,
    kPitchFieldNumber = 7,
    kYawFieldNumber = 8,
    kRollFieldNumber = 9,
  };
  // uint32 zombieid = 1;
  void clear_zombieid();
  uint32_t zombieid() const;
  void set_zombieid(uint32_t value);
  private:
  uint32_t _internal_zombieid() const;
  void _internal_set_zombieid(uint32_t value);
  public:

  // uint32 zombietype = 2;
  void clear_zombietype();
  uint32_t zombietype() const;
  void set_zombietype(uint32_t value);
  private:
  uint32_t _internal_zombietype() const;
  void _internal_set_zombietype(uint32_t value);
  public:

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // float x = 4;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 5;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 6;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float pitch = 7;
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // float yaw = 8;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // float roll = 9;
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Zombie)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t zombieid_;
    uint32_t zombietype_;
    uint32_t packet_type_;
    float x_;
    float y_;
    float z_;
    float pitch_;
    float yaw_;
    float roll_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// -------------------------------------------------------------------

class ZombieDataList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ZombieDataList) */ {
 public:
  inline ZombieDataList() : ZombieDataList(nullptr) {}
  ~ZombieDataList() override;
  explicit PROTOBUF_CONSTEXPR ZombieDataList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ZombieDataList(const ZombieDataList& from);
  ZombieDataList(ZombieDataList&& from) noexcept
    : ZombieDataList() {
    *this = ::std::move(from);
  }

  inline ZombieDataList& operator=(const ZombieDataList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ZombieDataList& operator=(ZombieDataList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ZombieDataList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ZombieDataList* internal_default_instance() {
    return reinterpret_cast<const ZombieDataList*>(
               &_ZombieDataList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ZombieDataList& a, ZombieDataList& b) {
    a.Swap(&b);
  }
  inline void Swap(ZombieDataList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ZombieDataList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ZombieDataList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ZombieDataList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ZombieDataList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ZombieDataList& from) {
    ZombieDataList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ZombieDataList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ZombieDataList";
  }
  protected:
  explicit ZombieDataList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kZombiesFieldNumber = 1,
    kPacketTypeFieldNumber = 3,
  };
  // repeated .Protocol.Zombie zombies = 1;
  int zombies_size() const;
  private:
  int _internal_zombies_size() const;
  public:
  void clear_zombies();
  ::Protocol::Zombie* mutable_zombies(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Zombie >*
      mutable_zombies();
  private:
  const ::Protocol::Zombie& _internal_zombies(int index) const;
  ::Protocol::Zombie* _internal_add_zombies();
  public:
  const ::Protocol::Zombie& zombies(int index) const;
  ::Protocol::Zombie* add_zombies();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Zombie >&
      zombies() const;

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ZombieDataList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Zombie > zombies_;
    uint32_t packet_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// -------------------------------------------------------------------

class Time final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Time) */ {
 public:
  inline Time() : Time(nullptr) {}
  ~Time() override;
  explicit PROTOBUF_CONSTEXPR Time(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Time(const Time& from);
  Time(Time&& from) noexcept
    : Time() {
    *this = ::std::move(from);
  }

  inline Time& operator=(const Time& from) {
    CopyFrom(from);
    return *this;
  }
  inline Time& operator=(Time&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Time& default_instance() {
    return *internal_default_instance();
  }
  static inline const Time* internal_default_instance() {
    return reinterpret_cast<const Time*>(
               &_Time_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Time& a, Time& b) {
    a.Swap(&b);
  }
  inline void Swap(Time* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Time* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Time* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Time>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Time& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Time& from) {
    Time::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Time* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Time";
  }
  protected:
  explicit Time(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimerFieldNumber = 1,
    kPacketTypeFieldNumber = 3,
  };
  // uint32 timer = 1;
  void clear_timer();
  uint32_t timer() const;
  void set_timer(uint32_t value);
  private:
  uint32_t _internal_timer() const;
  void _internal_set_timer(uint32_t value);
  public:

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Time)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t timer_;
    uint32_t packet_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// -------------------------------------------------------------------

class Character_Attack final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Character_Attack) */ {
 public:
  inline Character_Attack() : Character_Attack(nullptr) {}
  ~Character_Attack() override;
  explicit PROTOBUF_CONSTEXPR Character_Attack(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Character_Attack(const Character_Attack& from);
  Character_Attack(Character_Attack&& from) noexcept
    : Character_Attack() {
    *this = ::std::move(from);
  }

  inline Character_Attack& operator=(const Character_Attack& from) {
    CopyFrom(from);
    return *this;
  }
  inline Character_Attack& operator=(Character_Attack&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Character_Attack& default_instance() {
    return *internal_default_instance();
  }
  static inline const Character_Attack* internal_default_instance() {
    return reinterpret_cast<const Character_Attack*>(
               &_Character_Attack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Character_Attack& a, Character_Attack& b) {
    a.Swap(&b);
  }
  inline void Swap(Character_Attack* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Character_Attack* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Character_Attack* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Character_Attack>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Character_Attack& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Character_Attack& from) {
    Character_Attack::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Character_Attack* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Character_Attack";
  }
  protected:
  explicit Character_Attack(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayeridFieldNumber = 1,
    kAttackFieldNumber = 2,
    kPacketTypeFieldNumber = 3,
  };
  // uint32 playerid = 1;
  void clear_playerid();
  uint32_t playerid() const;
  void set_playerid(uint32_t value);
  private:
  uint32_t _internal_playerid() const;
  void _internal_set_playerid(uint32_t value);
  public:

  // bool attack = 2;
  void clear_attack();
  bool attack() const;
  void set_attack(bool value);
  private:
  bool _internal_attack() const;
  void _internal_set_attack(bool value);
  public:

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Character_Attack)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t playerid_;
    bool attack_;
    uint32_t packet_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// -------------------------------------------------------------------

class Equip_Item final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Equip_Item) */ {
 public:
  inline Equip_Item() : Equip_Item(nullptr) {}
  ~Equip_Item() override;
  explicit PROTOBUF_CONSTEXPR Equip_Item(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Equip_Item(const Equip_Item& from);
  Equip_Item(Equip_Item&& from) noexcept
    : Equip_Item() {
    *this = ::std::move(from);
  }

  inline Equip_Item& operator=(const Equip_Item& from) {
    CopyFrom(from);
    return *this;
  }
  inline Equip_Item& operator=(Equip_Item&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Equip_Item& default_instance() {
    return *internal_default_instance();
  }
  static inline const Equip_Item* internal_default_instance() {
    return reinterpret_cast<const Equip_Item*>(
               &_Equip_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Equip_Item& a, Equip_Item& b) {
    a.Swap(&b);
  }
  inline void Swap(Equip_Item* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Equip_Item* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Equip_Item* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Equip_Item>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Equip_Item& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Equip_Item& from) {
    Equip_Item::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Equip_Item* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Equip_Item";
  }
  protected:
  explicit Equip_Item(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemnameFieldNumber = 2,
    kPlayeridFieldNumber = 1,
    kPacketTypeFieldNumber = 3,
    kItemtypeFieldNumber = 4,
  };
  // string itemname = 2;
  void clear_itemname();
  const std::string& itemname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_itemname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_itemname();
  PROTOBUF_NODISCARD std::string* release_itemname();
  void set_allocated_itemname(std::string* itemname);
  private:
  const std::string& _internal_itemname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_itemname(const std::string& value);
  std::string* _internal_mutable_itemname();
  public:

  // uint32 playerid = 1;
  void clear_playerid();
  uint32_t playerid() const;
  void set_playerid(uint32_t value);
  private:
  uint32_t _internal_playerid() const;
  void _internal_set_playerid(uint32_t value);
  public:

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // uint32 itemtype = 4;
  void clear_itemtype();
  uint32_t itemtype() const;
  void set_itemtype(uint32_t value);
  private:
  uint32_t _internal_itemtype() const;
  void _internal_set_itemtype(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Equip_Item)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr itemname_;
    uint32_t playerid_;
    uint32_t packet_type_;
    uint32_t itemtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// -------------------------------------------------------------------

class run final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.run) */ {
 public:
  inline run() : run(nullptr) {}
  ~run() override;
  explicit PROTOBUF_CONSTEXPR run(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  run(const run& from);
  run(run&& from) noexcept
    : run() {
    *this = ::std::move(from);
  }

  inline run& operator=(const run& from) {
    CopyFrom(from);
    return *this;
  }
  inline run& operator=(run&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const run& default_instance() {
    return *internal_default_instance();
  }
  static inline const run* internal_default_instance() {
    return reinterpret_cast<const run*>(
               &_run_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(run& a, run& b) {
    a.Swap(&b);
  }
  inline void Swap(run* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(run* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  run* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<run>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const run& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const run& from) {
    run::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(run* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.run";
  }
  protected:
  explicit run(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayeridFieldNumber = 1,
    kBRunFieldNumber = 2,
    kPacketTypeFieldNumber = 3,
  };
  // uint32 playerid = 1;
  void clear_playerid();
  uint32_t playerid() const;
  void set_playerid(uint32_t value);
  private:
  uint32_t _internal_playerid() const;
  void _internal_set_playerid(uint32_t value);
  public:

  // bool b_run = 2;
  void clear_b_run();
  bool b_run() const;
  void set_b_run(bool value);
  private:
  bool _internal_b_run() const;
  void _internal_set_b_run(bool value);
  public:

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.run)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t playerid_;
    bool b_run_;
    uint32_t packet_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// -------------------------------------------------------------------

class jump final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.jump) */ {
 public:
  inline jump() : jump(nullptr) {}
  ~jump() override;
  explicit PROTOBUF_CONSTEXPR jump(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  jump(const jump& from);
  jump(jump&& from) noexcept
    : jump() {
    *this = ::std::move(from);
  }

  inline jump& operator=(const jump& from) {
    CopyFrom(from);
    return *this;
  }
  inline jump& operator=(jump&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const jump& default_instance() {
    return *internal_default_instance();
  }
  static inline const jump* internal_default_instance() {
    return reinterpret_cast<const jump*>(
               &_jump_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(jump& a, jump& b) {
    a.Swap(&b);
  }
  inline void Swap(jump* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(jump* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  jump* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<jump>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const jump& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const jump& from) {
    jump::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(jump* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.jump";
  }
  protected:
  explicit jump(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayeridFieldNumber = 1,
    kPacketTypeFieldNumber = 3,
  };
  // uint32 playerid = 1;
  void clear_playerid();
  uint32_t playerid() const;
  void set_playerid(uint32_t value);
  private:
  uint32_t _internal_playerid() const;
  void _internal_set_playerid(uint32_t value);
  public:

  // uint32 packet_type = 3;
  void clear_packet_type();
  uint32_t packet_type() const;
  void set_packet_type(uint32_t value);
  private:
  uint32_t _internal_packet_type() const;
  void _internal_set_packet_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.jump)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t playerid_;
    uint32_t packet_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GStruct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Character

// uint32 playerid = 1;
inline void Character::clear_playerid() {
  _impl_.playerid_ = 0u;
}
inline uint32_t Character::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint32_t Character::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.playerid)
  return _internal_playerid();
}
inline void Character::_internal_set_playerid(uint32_t value) {
  
  _impl_.playerid_ = value;
}
inline void Character::set_playerid(uint32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.playerid)
}

// uint32 charactertype = 2;
inline void Character::clear_charactertype() {
  _impl_.charactertype_ = 0u;
}
inline uint32_t Character::_internal_charactertype() const {
  return _impl_.charactertype_;
}
inline uint32_t Character::charactertype() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.charactertype)
  return _internal_charactertype();
}
inline void Character::_internal_set_charactertype(uint32_t value) {
  
  _impl_.charactertype_ = value;
}
inline void Character::set_charactertype(uint32_t value) {
  _internal_set_charactertype(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.charactertype)
}

// uint32 packet_type = 3;
inline void Character::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t Character::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t Character::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.packet_type)
  return _internal_packet_type();
}
inline void Character::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Character::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.packet_type)
}

// float x = 4;
inline void Character::clear_x() {
  _impl_.x_ = 0;
}
inline float Character::_internal_x() const {
  return _impl_.x_;
}
inline float Character::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.x)
  return _internal_x();
}
inline void Character::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Character::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.x)
}

// float y = 5;
inline void Character::clear_y() {
  _impl_.y_ = 0;
}
inline float Character::_internal_y() const {
  return _impl_.y_;
}
inline float Character::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.y)
  return _internal_y();
}
inline void Character::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Character::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.y)
}

// float z = 6;
inline void Character::clear_z() {
  _impl_.z_ = 0;
}
inline float Character::_internal_z() const {
  return _impl_.z_;
}
inline float Character::z() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.z)
  return _internal_z();
}
inline void Character::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Character::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.z)
}

// float pitch = 7;
inline void Character::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline float Character::_internal_pitch() const {
  return _impl_.pitch_;
}
inline float Character::pitch() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.pitch)
  return _internal_pitch();
}
inline void Character::_internal_set_pitch(float value) {
  
  _impl_.pitch_ = value;
}
inline void Character::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.pitch)
}

// float yaw = 8;
inline void Character::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float Character::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float Character::yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.yaw)
  return _internal_yaw();
}
inline void Character::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void Character::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.yaw)
}

// float roll = 9;
inline void Character::clear_roll() {
  _impl_.roll_ = 0;
}
inline float Character::_internal_roll() const {
  return _impl_.roll_;
}
inline float Character::roll() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.roll)
  return _internal_roll();
}
inline void Character::_internal_set_roll(float value) {
  
  _impl_.roll_ = value;
}
inline void Character::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.roll)
}

// float hp = 10;
inline void Character::clear_hp() {
  _impl_.hp_ = 0;
}
inline float Character::_internal_hp() const {
  return _impl_.hp_;
}
inline float Character::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.hp)
  return _internal_hp();
}
inline void Character::_internal_set_hp(float value) {
  
  _impl_.hp_ = value;
}
inline void Character::set_hp(float value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.hp)
}

// bool isingame = 11;
inline void Character::clear_isingame() {
  _impl_.isingame_ = false;
}
inline bool Character::_internal_isingame() const {
  return _impl_.isingame_;
}
inline bool Character::isingame() const {
  // @@protoc_insertion_point(field_get:Protocol.Character.isingame)
  return _internal_isingame();
}
inline void Character::_internal_set_isingame(bool value) {
  
  _impl_.isingame_ = value;
}
inline void Character::set_isingame(bool value) {
  _internal_set_isingame(value);
  // @@protoc_insertion_point(field_set:Protocol.Character.isingame)
}

// -------------------------------------------------------------------

// Zombie

// uint32 zombieid = 1;
inline void Zombie::clear_zombieid() {
  _impl_.zombieid_ = 0u;
}
inline uint32_t Zombie::_internal_zombieid() const {
  return _impl_.zombieid_;
}
inline uint32_t Zombie::zombieid() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.zombieid)
  return _internal_zombieid();
}
inline void Zombie::_internal_set_zombieid(uint32_t value) {
  
  _impl_.zombieid_ = value;
}
inline void Zombie::set_zombieid(uint32_t value) {
  _internal_set_zombieid(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.zombieid)
}

// uint32 zombietype = 2;
inline void Zombie::clear_zombietype() {
  _impl_.zombietype_ = 0u;
}
inline uint32_t Zombie::_internal_zombietype() const {
  return _impl_.zombietype_;
}
inline uint32_t Zombie::zombietype() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.zombietype)
  return _internal_zombietype();
}
inline void Zombie::_internal_set_zombietype(uint32_t value) {
  
  _impl_.zombietype_ = value;
}
inline void Zombie::set_zombietype(uint32_t value) {
  _internal_set_zombietype(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.zombietype)
}

// uint32 packet_type = 3;
inline void Zombie::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t Zombie::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t Zombie::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.packet_type)
  return _internal_packet_type();
}
inline void Zombie::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Zombie::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.packet_type)
}

// float x = 4;
inline void Zombie::clear_x() {
  _impl_.x_ = 0;
}
inline float Zombie::_internal_x() const {
  return _impl_.x_;
}
inline float Zombie::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.x)
  return _internal_x();
}
inline void Zombie::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Zombie::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.x)
}

// float y = 5;
inline void Zombie::clear_y() {
  _impl_.y_ = 0;
}
inline float Zombie::_internal_y() const {
  return _impl_.y_;
}
inline float Zombie::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.y)
  return _internal_y();
}
inline void Zombie::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Zombie::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.y)
}

// float z = 6;
inline void Zombie::clear_z() {
  _impl_.z_ = 0;
}
inline float Zombie::_internal_z() const {
  return _impl_.z_;
}
inline float Zombie::z() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.z)
  return _internal_z();
}
inline void Zombie::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Zombie::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.z)
}

// float pitch = 7;
inline void Zombie::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline float Zombie::_internal_pitch() const {
  return _impl_.pitch_;
}
inline float Zombie::pitch() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.pitch)
  return _internal_pitch();
}
inline void Zombie::_internal_set_pitch(float value) {
  
  _impl_.pitch_ = value;
}
inline void Zombie::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.pitch)
}

// float yaw = 8;
inline void Zombie::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float Zombie::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float Zombie::yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.yaw)
  return _internal_yaw();
}
inline void Zombie::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void Zombie::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.yaw)
}

// float roll = 9;
inline void Zombie::clear_roll() {
  _impl_.roll_ = 0;
}
inline float Zombie::_internal_roll() const {
  return _impl_.roll_;
}
inline float Zombie::roll() const {
  // @@protoc_insertion_point(field_get:Protocol.Zombie.roll)
  return _internal_roll();
}
inline void Zombie::_internal_set_roll(float value) {
  
  _impl_.roll_ = value;
}
inline void Zombie::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:Protocol.Zombie.roll)
}

// -------------------------------------------------------------------

// ZombieDataList

// repeated .Protocol.Zombie zombies = 1;
inline int ZombieDataList::_internal_zombies_size() const {
  return _impl_.zombies_.size();
}
inline int ZombieDataList::zombies_size() const {
  return _internal_zombies_size();
}
inline void ZombieDataList::clear_zombies() {
  _impl_.zombies_.Clear();
}
inline ::Protocol::Zombie* ZombieDataList::mutable_zombies(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.ZombieDataList.zombies)
  return _impl_.zombies_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Zombie >*
ZombieDataList::mutable_zombies() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.ZombieDataList.zombies)
  return &_impl_.zombies_;
}
inline const ::Protocol::Zombie& ZombieDataList::_internal_zombies(int index) const {
  return _impl_.zombies_.Get(index);
}
inline const ::Protocol::Zombie& ZombieDataList::zombies(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.ZombieDataList.zombies)
  return _internal_zombies(index);
}
inline ::Protocol::Zombie* ZombieDataList::_internal_add_zombies() {
  return _impl_.zombies_.Add();
}
inline ::Protocol::Zombie* ZombieDataList::add_zombies() {
  ::Protocol::Zombie* _add = _internal_add_zombies();
  // @@protoc_insertion_point(field_add:Protocol.ZombieDataList.zombies)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Zombie >&
ZombieDataList::zombies() const {
  // @@protoc_insertion_point(field_list:Protocol.ZombieDataList.zombies)
  return _impl_.zombies_;
}

// uint32 packet_type = 3;
inline void ZombieDataList::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t ZombieDataList::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t ZombieDataList::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.ZombieDataList.packet_type)
  return _internal_packet_type();
}
inline void ZombieDataList::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void ZombieDataList::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.ZombieDataList.packet_type)
}

// -------------------------------------------------------------------

// Time

// uint32 timer = 1;
inline void Time::clear_timer() {
  _impl_.timer_ = 0u;
}
inline uint32_t Time::_internal_timer() const {
  return _impl_.timer_;
}
inline uint32_t Time::timer() const {
  // @@protoc_insertion_point(field_get:Protocol.Time.timer)
  return _internal_timer();
}
inline void Time::_internal_set_timer(uint32_t value) {
  
  _impl_.timer_ = value;
}
inline void Time::set_timer(uint32_t value) {
  _internal_set_timer(value);
  // @@protoc_insertion_point(field_set:Protocol.Time.timer)
}

// uint32 packet_type = 3;
inline void Time::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t Time::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t Time::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.Time.packet_type)
  return _internal_packet_type();
}
inline void Time::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Time::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.Time.packet_type)
}

// -------------------------------------------------------------------

// Character_Attack

// uint32 playerid = 1;
inline void Character_Attack::clear_playerid() {
  _impl_.playerid_ = 0u;
}
inline uint32_t Character_Attack::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint32_t Character_Attack::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.Character_Attack.playerid)
  return _internal_playerid();
}
inline void Character_Attack::_internal_set_playerid(uint32_t value) {
  
  _impl_.playerid_ = value;
}
inline void Character_Attack::set_playerid(uint32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.Character_Attack.playerid)
}

// bool attack = 2;
inline void Character_Attack::clear_attack() {
  _impl_.attack_ = false;
}
inline bool Character_Attack::_internal_attack() const {
  return _impl_.attack_;
}
inline bool Character_Attack::attack() const {
  // @@protoc_insertion_point(field_get:Protocol.Character_Attack.attack)
  return _internal_attack();
}
inline void Character_Attack::_internal_set_attack(bool value) {
  
  _impl_.attack_ = value;
}
inline void Character_Attack::set_attack(bool value) {
  _internal_set_attack(value);
  // @@protoc_insertion_point(field_set:Protocol.Character_Attack.attack)
}

// uint32 packet_type = 3;
inline void Character_Attack::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t Character_Attack::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t Character_Attack::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.Character_Attack.packet_type)
  return _internal_packet_type();
}
inline void Character_Attack::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Character_Attack::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.Character_Attack.packet_type)
}

// -------------------------------------------------------------------

// Equip_Item

// uint32 playerid = 1;
inline void Equip_Item::clear_playerid() {
  _impl_.playerid_ = 0u;
}
inline uint32_t Equip_Item::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint32_t Equip_Item::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.Equip_Item.playerid)
  return _internal_playerid();
}
inline void Equip_Item::_internal_set_playerid(uint32_t value) {
  
  _impl_.playerid_ = value;
}
inline void Equip_Item::set_playerid(uint32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.Equip_Item.playerid)
}

// string itemname = 2;
inline void Equip_Item::clear_itemname() {
  _impl_.itemname_.ClearToEmpty();
}
inline const std::string& Equip_Item::itemname() const {
  // @@protoc_insertion_point(field_get:Protocol.Equip_Item.itemname)
  return _internal_itemname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Equip_Item::set_itemname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.itemname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.Equip_Item.itemname)
}
inline std::string* Equip_Item::mutable_itemname() {
  std::string* _s = _internal_mutable_itemname();
  // @@protoc_insertion_point(field_mutable:Protocol.Equip_Item.itemname)
  return _s;
}
inline const std::string& Equip_Item::_internal_itemname() const {
  return _impl_.itemname_.Get();
}
inline void Equip_Item::_internal_set_itemname(const std::string& value) {
  
  _impl_.itemname_.Set(value, GetArenaForAllocation());
}
inline std::string* Equip_Item::_internal_mutable_itemname() {
  
  return _impl_.itemname_.Mutable(GetArenaForAllocation());
}
inline std::string* Equip_Item::release_itemname() {
  // @@protoc_insertion_point(field_release:Protocol.Equip_Item.itemname)
  return _impl_.itemname_.Release();
}
inline void Equip_Item::set_allocated_itemname(std::string* itemname) {
  if (itemname != nullptr) {
    
  } else {
    
  }
  _impl_.itemname_.SetAllocated(itemname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.itemname_.IsDefault()) {
    _impl_.itemname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.Equip_Item.itemname)
}

// uint32 packet_type = 3;
inline void Equip_Item::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t Equip_Item::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t Equip_Item::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.Equip_Item.packet_type)
  return _internal_packet_type();
}
inline void Equip_Item::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Equip_Item::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.Equip_Item.packet_type)
}

// uint32 itemtype = 4;
inline void Equip_Item::clear_itemtype() {
  _impl_.itemtype_ = 0u;
}
inline uint32_t Equip_Item::_internal_itemtype() const {
  return _impl_.itemtype_;
}
inline uint32_t Equip_Item::itemtype() const {
  // @@protoc_insertion_point(field_get:Protocol.Equip_Item.itemtype)
  return _internal_itemtype();
}
inline void Equip_Item::_internal_set_itemtype(uint32_t value) {
  
  _impl_.itemtype_ = value;
}
inline void Equip_Item::set_itemtype(uint32_t value) {
  _internal_set_itemtype(value);
  // @@protoc_insertion_point(field_set:Protocol.Equip_Item.itemtype)
}

// -------------------------------------------------------------------

// run

// uint32 playerid = 1;
inline void run::clear_playerid() {
  _impl_.playerid_ = 0u;
}
inline uint32_t run::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint32_t run::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.run.playerid)
  return _internal_playerid();
}
inline void run::_internal_set_playerid(uint32_t value) {
  
  _impl_.playerid_ = value;
}
inline void run::set_playerid(uint32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.run.playerid)
}

// bool b_run = 2;
inline void run::clear_b_run() {
  _impl_.b_run_ = false;
}
inline bool run::_internal_b_run() const {
  return _impl_.b_run_;
}
inline bool run::b_run() const {
  // @@protoc_insertion_point(field_get:Protocol.run.b_run)
  return _internal_b_run();
}
inline void run::_internal_set_b_run(bool value) {
  
  _impl_.b_run_ = value;
}
inline void run::set_b_run(bool value) {
  _internal_set_b_run(value);
  // @@protoc_insertion_point(field_set:Protocol.run.b_run)
}

// uint32 packet_type = 3;
inline void run::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t run::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t run::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.run.packet_type)
  return _internal_packet_type();
}
inline void run::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void run::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.run.packet_type)
}

// -------------------------------------------------------------------

// jump

// uint32 playerid = 1;
inline void jump::clear_playerid() {
  _impl_.playerid_ = 0u;
}
inline uint32_t jump::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint32_t jump::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.jump.playerid)
  return _internal_playerid();
}
inline void jump::_internal_set_playerid(uint32_t value) {
  
  _impl_.playerid_ = value;
}
inline void jump::set_playerid(uint32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.jump.playerid)
}

// uint32 packet_type = 3;
inline void jump::clear_packet_type() {
  _impl_.packet_type_ = 0u;
}
inline uint32_t jump::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline uint32_t jump::packet_type() const {
  // @@protoc_insertion_point(field_get:Protocol.jump.packet_type)
  return _internal_packet_type();
}
inline void jump::_internal_set_packet_type(uint32_t value) {
  
  _impl_.packet_type_ = value;
}
inline void jump::set_packet_type(uint32_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:Protocol.jump.packet_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_GStruct_2eproto
