// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LStruct.proto

#include "LStruct.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR CS_Login::CS_Login(
    ::_pbi::ConstantInitialized) {}
struct CS_LoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_LoginDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_LoginDefaultTypeInternal() {}
  union {
    CS_Login _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_LoginDefaultTypeInternal _CS_Login_default_instance_;
PROTOBUF_CONSTEXPR SC_Login::SC_Login(
    ::_pbi::ConstantInitialized) {}
struct SC_LoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_LoginDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_LoginDefaultTypeInternal() {}
  union {
    SC_Login _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_LoginDefaultTypeInternal _SC_Login_default_instance_;
PROTOBUF_CONSTEXPR CS_Ready::CS_Ready(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.playerid_)*/0u
  , /*decltype(_impl_.ready_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CS_ReadyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_ReadyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_ReadyDefaultTypeInternal() {}
  union {
    CS_Ready _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_ReadyDefaultTypeInternal _CS_Ready_default_instance_;
PROTOBUF_CONSTEXPR SC_Ready::SC_Ready(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.allready_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SC_ReadyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_ReadyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_ReadyDefaultTypeInternal() {}
  union {
    SC_Ready _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_ReadyDefaultTypeInternal _SC_Ready_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_LStruct_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_LStruct_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_LStruct_2eproto = nullptr;

const uint32_t TableStruct_LStruct_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_Login, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::SC_Login, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_Ready, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_Ready, _impl_.playerid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::CS_Ready, _impl_.ready_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::SC_Ready, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::SC_Ready, _impl_.allready_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::CS_Login)},
  { 6, -1, -1, sizeof(::Protocol::SC_Login)},
  { 12, -1, -1, sizeof(::Protocol::CS_Ready)},
  { 20, -1, -1, sizeof(::Protocol::SC_Ready)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_CS_Login_default_instance_._instance,
  &::Protocol::_SC_Login_default_instance_._instance,
  &::Protocol::_CS_Ready_default_instance_._instance,
  &::Protocol::_SC_Ready_default_instance_._instance,
};

const char descriptor_table_protodef_LStruct_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rLStruct.proto\022\010Protocol\"\n\n\010CS_Login\"\n\n"
  "\010SC_Login\"+\n\010CS_Ready\022\020\n\010playerid\030\001 \001(\r\022"
  "\r\n\005ready\030\002 \001(\010\"\034\n\010SC_Ready\022\020\n\010allready\030\001"
  " \001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_LStruct_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_LStruct_2eproto = {
    false, false, 132, descriptor_table_protodef_LStruct_2eproto,
    "LStruct.proto",
    &descriptor_table_LStruct_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_LStruct_2eproto::offsets,
    file_level_metadata_LStruct_2eproto, file_level_enum_descriptors_LStruct_2eproto,
    file_level_service_descriptors_LStruct_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_LStruct_2eproto_getter() {
  return &descriptor_table_LStruct_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_LStruct_2eproto(&descriptor_table_LStruct_2eproto);
namespace Protocol {

// ===================================================================

class CS_Login::_Internal {
 public:
};

CS_Login::CS_Login(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_Login)
}
CS_Login::CS_Login(const CS_Login& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  CS_Login* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.CS_Login)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CS_Login::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CS_Login::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata CS_Login::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LStruct_2eproto_getter, &descriptor_table_LStruct_2eproto_once,
      file_level_metadata_LStruct_2eproto[0]);
}

// ===================================================================

class SC_Login::_Internal {
 public:
};

SC_Login::SC_Login(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_Login)
}
SC_Login::SC_Login(const SC_Login& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  SC_Login* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.SC_Login)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SC_Login::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SC_Login::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata SC_Login::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LStruct_2eproto_getter, &descriptor_table_LStruct_2eproto_once,
      file_level_metadata_LStruct_2eproto[1]);
}

// ===================================================================

class CS_Ready::_Internal {
 public:
};

CS_Ready::CS_Ready(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_Ready)
}
CS_Ready::CS_Ready(const CS_Ready& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CS_Ready* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.playerid_){}
    , decltype(_impl_.ready_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.playerid_, &from._impl_.playerid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ready_) -
    reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.ready_));
  // @@protoc_insertion_point(copy_constructor:Protocol.CS_Ready)
}

inline void CS_Ready::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.playerid_){0u}
    , decltype(_impl_.ready_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CS_Ready::~CS_Ready() {
  // @@protoc_insertion_point(destructor:Protocol.CS_Ready)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CS_Ready::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CS_Ready::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CS_Ready::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_Ready)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ready_) -
      reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.ready_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CS_Ready::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 playerid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.playerid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ready = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ready_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CS_Ready::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_Ready)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 playerid = 1;
  if (this->_internal_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_playerid(), target);
  }

  // bool ready = 2;
  if (this->_internal_ready() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_ready(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_Ready)
  return target;
}

size_t CS_Ready::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.CS_Ready)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 playerid = 1;
  if (this->_internal_playerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_playerid());
  }

  // bool ready = 2;
  if (this->_internal_ready() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CS_Ready::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CS_Ready::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CS_Ready::GetClassData() const { return &_class_data_; }


void CS_Ready::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CS_Ready*>(&to_msg);
  auto& from = static_cast<const CS_Ready&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_Ready)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_playerid() != 0) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  if (from._internal_ready() != 0) {
    _this->_internal_set_ready(from._internal_ready());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CS_Ready::CopyFrom(const CS_Ready& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_Ready)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_Ready::IsInitialized() const {
  return true;
}

void CS_Ready::InternalSwap(CS_Ready* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CS_Ready, _impl_.ready_)
      + sizeof(CS_Ready::_impl_.ready_)
      - PROTOBUF_FIELD_OFFSET(CS_Ready, _impl_.playerid_)>(
          reinterpret_cast<char*>(&_impl_.playerid_),
          reinterpret_cast<char*>(&other->_impl_.playerid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CS_Ready::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LStruct_2eproto_getter, &descriptor_table_LStruct_2eproto_once,
      file_level_metadata_LStruct_2eproto[2]);
}

// ===================================================================

class SC_Ready::_Internal {
 public:
};

SC_Ready::SC_Ready(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_Ready)
}
SC_Ready::SC_Ready(const SC_Ready& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SC_Ready* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.allready_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.allready_ = from._impl_.allready_;
  // @@protoc_insertion_point(copy_constructor:Protocol.SC_Ready)
}

inline void SC_Ready::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.allready_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SC_Ready::~SC_Ready() {
  // @@protoc_insertion_point(destructor:Protocol.SC_Ready)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SC_Ready::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SC_Ready::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SC_Ready::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_Ready)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.allready_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SC_Ready::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool allready = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.allready_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SC_Ready::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_Ready)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool allready = 1;
  if (this->_internal_allready() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_allready(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_Ready)
  return target;
}

size_t SC_Ready::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.SC_Ready)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool allready = 1;
  if (this->_internal_allready() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SC_Ready::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SC_Ready::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SC_Ready::GetClassData() const { return &_class_data_; }


void SC_Ready::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SC_Ready*>(&to_msg);
  auto& from = static_cast<const SC_Ready&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_Ready)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_allready() != 0) {
    _this->_internal_set_allready(from._internal_allready());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SC_Ready::CopyFrom(const SC_Ready& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_Ready)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SC_Ready::IsInitialized() const {
  return true;
}

void SC_Ready::InternalSwap(SC_Ready* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.allready_, other->_impl_.allready_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SC_Ready::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_LStruct_2eproto_getter, &descriptor_table_LStruct_2eproto_once,
      file_level_metadata_LStruct_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::CS_Login*
Arena::CreateMaybeMessage< ::Protocol::CS_Login >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CS_Login >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::SC_Login*
Arena::CreateMaybeMessage< ::Protocol::SC_Login >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::SC_Login >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::CS_Ready*
Arena::CreateMaybeMessage< ::Protocol::CS_Ready >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::CS_Ready >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::SC_Ready*
Arena::CreateMaybeMessage< ::Protocol::SC_Ready >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::SC_Ready >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
